version: '3.8'

services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports:
      - "1434:1433"
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=YourStrong@Passw0rd
    networks:
      - backend-net

  sql-init:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver
    entrypoint: >
      bash -c "
      sleep 20 &&
      /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P 'YourStrong@Passw0rd' -i /init/init.sql
      "
    volumes:
      - ./init:/init
    networks:
      - backend-net

  backend:
    build: .
    container_name: backend
    depends_on:
      - sqlserver
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://sqlserver:1433;databaseName=Gym;encrypt=true;trustServerCertificate=true
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=YourStrong@Passw0rd
      - JWT_SECRET=Ot+WMUGdAJtk7Zqhkqc7IVHlhDGQE2a8qbbIbHlbzVJ6yngs3MMSn0pro7AR9rfl
      - JWT_EXPIRATION=3600000
    ports:
      - "8000:8000"
    networks:
      - backend-net

networks:
  backend-net:
